contractions = {  
"ain't": "am not", 
"aren't": "are not", 
"can't": "cannot", 
"'cause": "because", 
"could've": "could have", 
"couldn't": "could not", 
"didn't": "did not", 
"doesn't": "does not", 
"don't": "do not", 
"hadn't": "had not", 
"hasn't": "has not", 
"haven't": "have not", 
"he'd": "he had", 
"he'll": "he will", 
"he's": "he is", 
"how'd": "how did", 
"how'll": "how will", 
"how's": "how is", 
"i'd": "i would", 
"i'll": "i will", 
"i'm": "i am", 
"i've": "i have", 
"isn't": "is not", 
"it'd": "it would", 
"it'll": "it will", 
"it's": "it is", 
"let's": "let us", 
"ma'am": "madam", 
"might've": "might have", 
"must've": "must have", 
"o'clock": "of the clock", 
"she'd": "she would", 
"she's": "she is", 
"should've": "should have", 
"shouldn't": "should not", 
"so've": "so have", 
"so's": "so is", 
"that'd": "that would", 
"that's": "that is", 
"there'd": "there would", 
"there's": "there is", 
"they'd": "they would", 
"they'll": "they will", 
"they're": "they are", 
"they've": "they have", 
"wasn't": "was not", 
"we'd": "we would", 
"we'll": "we will", 
"we're": "we are", 
"we've": "we have", 
"weren't": "were not", 
"what'll": "what will", 
"what're": "what are", 
"what's": "what is", 
"what've": "what have", 
"when's": "when is", 
"where'd": "where did", 
"where's": "where is", 
"who'll": "who will", 
"who's": "who is", 
"why's": "why is", 
"won't": "will not", 
"would've": "would have", 
"wouldn't": "would not", 
"y'all": "you all", 
"you'd": "you would", 
"you'll": "you will", 
"you're": "you are", 
"you've": "you have" 
} 
	 

stop_words =[ 'ourselves', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again','then', 'once', 'here', 'there', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 'can', 'will', 'just', "don't", 'should', "should've", "aren't", "couldn't", "didn't", "doesn't","hadn't", "hasn't", "haven't", "isn't", "shouldn't", "wasn't", "weren't", "won't", "wouldn't"] 
